# Generated by Django 5.2.13 on 2026-04-15 08:47

from django.db import migrations, models
from django.utils.text import slugify


def populate_department_slugs(apps, schema_editor):
    Department = apps.get_model('lms', 'Department')
    for department in Department.objects.all():
        if department.slug:
            continue
        base_slug = slugify(department.name) or f"department-{department.pk}"
        slug = base_slug
        counter = 1
        while Department.objects.filter(slug=slug).exclude(pk=department.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        department.slug = slug
        department.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_department_slugs, migrations.RunPython.noop),
    ]
