# Generated by Django 5.2.13 on 2026-04-15 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_department_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('document', 'Document (PDF, PowerPoint, Excel)'), ('video', 'Video')], default='document', max_length=20)),
                ('title', models.CharField(help_text='Title of the material', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the material')),
                ('file', models.FileField(blank=True, help_text='Upload PDF, PowerPoint, or Excel files', upload_to='chapter_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pptx', 'ppt', 'xlsx', 'xls', 'doc', 'docx'])])),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo or self-hosted video URL (optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lms.chapter')),
            ],
            options={
                'ordering': ['chapter', 'order', 'id'],
                'indexes': [models.Index(fields=['chapter', 'order'], name='lms_chapter_chapter_e94490_idx'), models.Index(fields=['material_type'], name='lms_chapter_materia_3190c1_idx')],
            },
        ),
    ]
