# Generated by Django 4.2.11 on 2026-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_chaptermaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='document_file',
            field=models.FileField(blank=True, help_text='Upload PDF, PowerPoint, or Excel documents', null=True, upload_to='chapter_documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('lesson', 'Lesson with Documents'), ('reading', 'Reading Material'), ('quiz', 'Quiz Only'), ('assignment', 'Assignment'), ('project', 'Project')], default='lesson', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo or self-hosted video URL (optional)'),
        ),
        migrations.DeleteModel(
            name='ChapterMaterial',
        ),
    ]
