# Generated by Django 4.2.11 on 2026-04-15 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_chapter_document_file_alter_chapter_chapter_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.FloatField(default=0.5, help_text='0 (easy) to 1 (very hard)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('estimated_learning_time', models.IntegerField(default=30, help_text='Minutes to master this concept')),
                ('embedding_vector', models.JSONField(default=list, help_text='768-dimensional embedding for semantic search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='lms.course')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Concepts that should be mastered first', to='lms.knowledgeconcept')),
            ],
            options={
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lesson_sequence', models.JSONField(default=list, help_text='Ordered list of lesson IDs')),
                ('target_audience', models.CharField(blank=True, help_text="e.g., 'Beginners', 'Advanced', 'Management'", max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='lms.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('video', 'Video Lesson'), ('text', 'Text Lesson'), ('rich_media', 'Rich Media (Interactive)'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('discussion', 'Discussion Forum'), ('project', 'Project'), ('resource', 'Resource Download'), ('external', 'External Content (SCORM/LTI)')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content', models.TextField(blank=True, help_text='HTML or rich text content for lesson')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.')),
                ('document_file', models.FileField(blank=True, help_text='PDF, PowerPoint, Excel files', upload_to='lesson_documents/%Y/%m/')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_free_preview', models.BooleanField(default=False, help_text='Accessible without enrollment')),
                ('requires_previous', models.BooleanField(default=True, help_text='Must complete previous lesson first')),
                ('downloadable_resources', models.JSONField(default=list, help_text='List of downloadable file URLs or file paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('unlock_condition', models.CharField(blank=True, help_text="e.g., 'previous_module:score:80' or 'course:quiz:pass'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lms.course')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lms.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RelatedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('prerequisite', 'Prerequisite - Must Learn First'), ('follow_up', 'Follow-up - Learn Next'), ('supplemental', 'Supplemental - Optional Extra Content'), ('alternative', 'Alternative Explanation'), ('deep_dive', 'Deep Dive - Advanced Version'), ('remedial', 'Remedial - Extra Help')], max_length=50)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence of relationship (for auto-generated)')),
                ('description', models.TextField(blank=True)),
                ('suggested_position', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('alongside', 'Alongside')], default='after', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='lms.lesson')),
                ('target_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereq_type', models.CharField(choices=[('course', 'Complete Course'), ('lesson', 'Complete Lesson'), ('quiz', 'Pass Quiz'), ('grade', 'Minimum Grade')], max_length=20)),
                ('prereq_id', models.PositiveIntegerField()),
                ('required_value', models.CharField(blank=True, help_text="e.g., '70' for grade out of 100", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_rules', to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20)),
                ('sections_completed', models.IntegerField(default=0)),
                ('total_sections', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lesson_resources/%Y/%m/')),
                ('file_type', models.CharField(max_length=20)),
                ('file_size_mb', models.FloatField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lms.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('video_progress_percentage', models.FloatField(default=0.0)),
                ('last_video_timestamp_seconds', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('assignment_score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('student_notes', models.TextField(blank=True)),
                ('bookmarked', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp_seconds', models.IntegerField(blank=True, null=True)),
                ('highlighted_text', models.TextField(blank=True)),
                ('highlight_color', models.CharField(default='#FFFF00', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.section'),
        ),
        migrations.CreateModel(
            name='LearningPathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lesson_index', models.IntegerField(default=0)),
                ('completed_lessons', models.JSONField(default=list)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.learningpath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_grade', models.FloatField(default=80.0, help_text='Target grade (0-100)')),
                ('target_completion_date', models.DateField()),
                ('weeks_available', models.IntegerField(default=12, help_text='Weeks left to complete goal')),
                ('weekly_hours_target', models.FloatField(default=5.0, help_text='Target hours per week')),
                ('actual_weekly_hours', models.JSONField(default=list, help_text='Weekly tracking: [{week_start, hours}]')),
                ('is_achieved', models.BooleanField(default=False)),
                ('current_progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemResponseTheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.FloatField(default=0.0, help_text='Item difficulty parameter (b)')),
                ('discrimination', models.FloatField(default=1.0, help_text='Item discrimination parameter (a)')),
                ('guessing', models.FloatField(default=0.2, help_text='Guessing parameter (c)')),
                ('sample_size', models.IntegerField(default=0)),
                ('is_calibrated', models.BooleanField(default=False)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irt', to='lms.question')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('weakness', 'Address Known Weakness'), ('strength', 'Build on Strength'), ('prerequisite', 'Prerequisites for next topic'), ('similar_content', 'Similar to liked content'), ('trending', 'Trending in your cohort'), ('peer_review', 'Recommended by peers')], max_length=50)),
                ('confidence', models.FloatField(default=0.0, help_text='1 = very confident, 0 = not confident', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('was_helpful', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptQuizSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('linear', 'Linear - Fixed Order'), ('adaptive_difficulty', 'Adaptive Difficulty'), ('concept_based', 'Concept Mastery Based'), ('irt', 'Item Response Theory')], default='adaptive_difficulty', max_length=50)),
                ('question_pool', models.JSONField(default=list)),
                ('completed_questions', models.JSONField(default=list)),
                ('estimated_ability', models.FloatField(default=0.0)),
                ('next_question_difficulty', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptLessonMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Importance weight (0-1)')),
                ('coverage_percentage', models.FloatField(default=100.0, help_text='Lesson coverage of this concept')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.knowledgeconcept')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptivePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation_lessons', models.JSONField(default=list, help_text='Lesson IDs for struggling students')),
                ('acceleration_lessons', models.JSONField(default=list, help_text='Advanced lessons for fast learners')),
                ('adaptive_difficulty', models.FloatField(default=0.5, help_text='0 (easy) to 1 (hard) - adjusts quiz difficulty')),
                ('predicted_completion_date', models.DateField(blank=True, null=True)),
                ('predicted_final_grade', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('current_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.lesson')),
                ('recommended_next', models.ForeignKey(blank=True, help_text='AI-recommended next lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_paths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('knowledge_state', models.FloatField(default=0.0)),
                ('slip_probability', models.FloatField(default=0.1)),
                ('guess_probability', models.FloatField(default=0.2)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('forgetting_curve', models.JSONField(default=list, help_text='Time-series of mastery decay: [{days_elapsed, score}]')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.knowledgeconcept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'mastery_score'], name='lms_student_student_32b446_idx'), models.Index(fields=['concept'], name='lms_student_concept_9af4a4_idx')],
                'unique_together': {('student', 'concept')},
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['module', 'order'], name='lms_section_module__f08814_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedcontent',
            unique_together={('source_lesson', 'target_lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('course', 'prereq_type', 'prereq_id')},
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['student', 'module'], name='lms_modulep_student_3372c4_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['status'], name='lms_modulep_status_8f813b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('student', 'module')},
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='lms_module_course__053625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['student', 'lesson'], name='lms_lessonp_student_9d15e4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['status'], name='lms_lessonp_status_b8a997_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['section', 'order'], name='lms_lesson_section_43f97e_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='lms_lesson_lesson__c3325d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathenrollment',
            unique_together={('student', 'learning_path')},
        ),
        migrations.AlterUniqueTogether(
            name='conceptlessonmapping',
            unique_together={('lesson', 'concept')},
        ),
        migrations.AlterUniqueTogether(
            name='adaptivepath',
            unique_together={('student', 'course')},
        ),
    ]
