# Generated by Django 4.2.11 on 2026-04-16 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_add_phase2b_adaptive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Module',
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('unlock_condition', models.CharField(blank=True, help_text="e.g., 'previous_module:score:80' or 'course:quiz:pass'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='module',
        ),
        migrations.RenameIndex(
            model_name='module',
            new_name='lms_module_code_39be84_idx',
            old_name='lms_departm_code_8477e6_idx',
        ),
        migrations.RenameIndex(
            model_name='module',
            new_name='lms_module_name_6161c2_idx',
            old_name='lms_departm_name_e6cd8e_idx',
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(help_text='Module code (e.g., BT, EME, CE)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['module_head', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='mission',
            field=models.TextField(blank=True, help_text='Module mission statement'),
        ),
        migrations.AlterField(
            model_name='module',
            name='vision',
            field=models.TextField(blank=True, help_text='Module vision statement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('instructor', 'Instructor'), ('learner', 'Learner'), ('module_head', 'Module Head'), ('approver', 'Approver')], default='learner', max_length=20),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.coursemodule'),
        ),
        migrations.AlterField(
            model_name='section',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lms.coursemodule'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'order'], name='lms_coursem_course__36266d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
    ]
