# Generated by Django 4.2.11 on 2026-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_coursemodule_rename_department_user_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='active', max_length=20),
        ),
    ]
