# Generated by Django 4.2.11 on 2026-04-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_add_module_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module_type',
            field=models.CharField(choices=[('technical', 'Technical Courses'), ('non_technical', 'Non-Technical Courses'), ('leadership', 'Leadership & Management')], default='technical', help_text='Categorize course into Technical, Non-Technical, or Leadership', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['module_type'], name='lms_course_module__b3fdbc_idx'),
        ),
    ]
