# Generated by Django 4.2.11 on 2026-04-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_add_course_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='lms.module'),
        ),
    ]
