# Generated by Django 4.2.11 on 2026-04-25 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_add_module_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination Period'), ('registration', 'Registration Period'), ('workshop', 'Workshop/Training'), ('seminar', 'Seminar'), ('career_fair', 'Career Fair'), ('open_day', 'Open Day'), ('graduation', 'Graduation Ceremony'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('meeting_link', models.URLField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE format', max_length=100)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('practical', 'Practical/Lab'), ('workshop', 'Workshop'), ('assessment', 'Assessment/Exam'), ('guest_lecture', 'Guest Lecture'), ('field_trip', 'Field Trip')], default='lecture', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('materials_needed', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('slides_url', models.URLField(blank=True)),
                ('additional_resources', models.JSONField(default=list)),
                ('attendance_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('attendance_taken', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('meeting_password', models.CharField(blank=True, max_length=50)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Advertisement'), ('featured', 'Featured Course'), ('flash_sale', 'Flash Sale'), ('scholarship', 'Scholarship Announcement'), ('early_bird', 'Early Bird Special')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(help_text='Short catchy headline', max_length=100)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='ad_banners/')),
                ('video_promo_url', models.URLField(blank=True)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('promo_code', models.CharField(blank=True, max_length=20)),
                ('offer_valid_until', models.DateTimeField(blank=True, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = more prominent')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('course_start', 'Course Start Reminder'), ('session_start', 'Session Start Reminder'), ('assignment_due', 'Assignment Due'), ('payment_due', 'Payment Due'), ('early_bird_end', 'Early Bird Deadline')], max_length=20)),
                ('send_at', models.DateTimeField(help_text='When to send the reminder')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Bricklaying Intake - March 2025'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('once', 'One-time Course'), ('recurring', 'Recurring Course'), ('rolling', 'Rolling Admission')], default='once', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('recurrence_end_date', models.DateTimeField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField(default=30)),
                ('current_enrolled', models.PositiveIntegerField(default=0)),
                ('waitlist_capacity', models.PositiveIntegerField(default=10)),
                ('session_duration_hours', models.PositiveIntegerField(default=4, help_text='Hours per session')),
                ('sessions_per_week', models.PositiveIntegerField(default=3)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online Live'), ('in_person', 'In Person'), ('hybrid', 'Hybrid'), ('self_paced', 'Self-Paced with Deadlines')], default='in_person', max_length=20)),
                ('venue', models.CharField(blank=True, max_length=500)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Teams/Google Meet link for online sessions')),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_deadline', models.DateTimeField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites, equipment needed')),
                ('what_to_expect', models.TextField(blank=True)),
                ('certification_provided', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('full', 'Fully Booked')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('dropped', 'Dropped'), ('completed', 'Completed'), ('certified', 'Certified')], default='enrolled', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('online', 'Online Attendance')], default='absent', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='schedule_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.scheduleenrollment'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='lms.classsession'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleenrollment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.courseschedule'),
        ),
        migrations.AddField(
            model_name='scheduleenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lms.course'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursereminder',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lms.courseschedule'),
        ),
        migrations.AddField(
            model_name='coursereminder',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.classsession'),
        ),
        migrations.AddField(
            model_name='courseadvertisement',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='lms.courseschedule'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lms.courseschedule'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='target_departments',
            field=models.ManyToManyField(blank=True, to='lms.module'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleenrollment',
            unique_together={('schedule', 'student')},
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['start_date', 'status'], name='lms_courses_start_d_0d6905_idx'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['course', 'is_featured'], name='lms_courses_course__a860c4_idx'),
        ),
    ]
