# Generated by Django 4.2.11 on 2026-04-30 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_calendarevent_classsession_courseadvertisement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g., 'CS0-003', 'CISSP-2024'", max_length=50, unique=True)),
                ('title', models.CharField(help_text="e.g., 'CompTIA Security+', 'Certified Ethical Hacker'", max_length=200)),
                ('full_title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('exam_code', models.CharField(blank=True, help_text='Official exam code', max_length=50)),
                ('exam_duration_minutes', models.PositiveIntegerField(default=90)),
                ('number_of_questions', models.PositiveIntegerField(default=90)),
                ('passing_score', models.PositiveIntegerField(default=750, help_text='Passing score (if scaled)')),
                ('passing_percentage', models.PositiveIntegerField(default=70, help_text='Passing percentage')),
                ('validity_years', models.PositiveIntegerField(default=3, help_text='Certification validity in years')),
                ('renewal_requirements', models.TextField(blank=True)),
                ('continuing_education_units', models.PositiveIntegerField(default=0, help_text='CEU required for renewal')),
                ('exam_voucher_price', models.DecimalField(decimal_places=2, default=0, help_text='Price for exam voucher', max_digits=10)),
                ('training_material_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('syllabus_pdf', models.FileField(blank=True, null=True, upload_to='certifications/syllabi/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certifications/logos/')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='certifications/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CertificationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'CompTIA', 'ISACA', 'EC-Council'", max_length=200)),
                ('short_name', models.CharField(help_text="e.g., 'CompTIA', 'CISA'", max_length=50)),
                ('provider_type', models.CharField(choices=[('global', 'Global Certification Body'), ('regional', 'Regional/African Body'), ('local', 'Zimbabwean Body'), ('vendor', 'Vendor-Specific')], default='global', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certification_partners/logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('partnership_status', models.CharField(choices=[('active', 'Active Partner'), ('pending', 'Pending Approval'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('partnership_start_date', models.DateField(blank=True, null=True)),
                ('partnership_end_date', models.DateField(blank=True, null=True)),
                ('partnership_agreement', models.FileField(blank=True, null=True, upload_to='certification_partners/agreements/')),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint for exam registration')),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook for result notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_voucher', models.BooleanField(default=True, help_text='Whether exam requires purchase of voucher')),
                ('voucher_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'March 2025 Intake'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about this intake')),
                ('registration_start_date', models.DateTimeField(help_text='When registration opens')),
                ('registration_end_date', models.DateTimeField(help_text='When registration closes')),
                ('course_start_date', models.DateTimeField(help_text='First day of course')),
                ('course_end_date', models.DateTimeField(help_text='Last day of course')),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=20)),
                ('start_time', models.TimeField(help_text='Class start time')),
                ('end_time', models.TimeField(help_text='Class end time')),
                ('duration_weeks', models.PositiveIntegerField(default=0, help_text='Total duration in weeks')),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Total course hours')),
                ('max_students', models.PositiveIntegerField(default=30, help_text='Maximum students allowed')),
                ('current_enrolled', models.PositiveIntegerField(default=0)),
                ('delivery_mode', models.CharField(choices=[('online', '💻 Online Live'), ('in_person', '🏛️ In Person'), ('hybrid', '🎯 Hybrid'), ('self_paced', '⚡ Self-Paced')], default='in_person', max_length=20)),
                ('venue', models.CharField(blank=True, help_text='Physical location for in-person', max_length=500)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Teams link for online')),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_deadline', models.DateTimeField(blank=True, help_text='Last day for early bird discount', null=True)),
                ('status', models.CharField(choices=[('upcoming', '📅 Upcoming'), ('open', '✅ Open for Registration'), ('in_progress', '🔄 In Progress'), ('completed', '✓ Completed'), ('cancelled', '❌ Cancelled'), ('full', '🔴 Fully Booked')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured section')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('exam_location', models.CharField(blank=True, help_text='Testing center location', max_length=500)),
                ('exam_language', models.CharField(default='English', max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, help_text='Exam voucher code', max_length=100)),
                ('voucher_expiry', models.DateField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, help_text='Reference ID from provider', max_length=200)),
                ('provider_candidate_id', models.CharField(blank=True, max_length=200)),
                ('exam_score', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_percentage', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('results_received_at', models.DateTimeField(blank=True, null=True)),
                ('results_details', models.JSONField(blank=True, default=dict, help_text='Detailed score report')),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_issue_date', models.DateField(blank=True, null=True)),
                ('certificate_expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='student_certificates/')),
                ('certificate_url', models.URLField(blank=True, help_text="Provider's verification URL")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('payment_verified', 'Payment Verified'), ('registered', 'Registered with Provider'), ('voucher_issued', 'Voucher Issued'), ('exam_scheduled', 'Exam Scheduled'), ('exam_completed', 'Exam Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('certificate_issued', 'Certificate Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='IntakeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Payment'), ('enrolled', '✅ Enrolled'), ('waitlisted', '📋 Waitlisted'), ('dropped', '❌ Dropped'), ('completed', '🎓 Completed'), ('certified', '🏆 Certified')], default='pending', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='Time of enrollment')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, help_text='Digital credential ID', max_length=100)),
                ('badge_url', models.URLField(blank=True, help_text='Digital badge URL')),
                ('verification_url', models.URLField(blank=True, help_text='Verification URL')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='scheduleenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scheduleenrollment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='scheduleenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='target_departments',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='target_roles',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='courseadvertisement',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coursereminder',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='schedule_enrollment',
        ),
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
        migrations.DeleteModel(
            name='ScheduleEnrollment',
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='lms.certification'),
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='exam_registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earned_certificate', to='lms.examregistration'),
        ),
        migrations.AddField(
            model_name='studentcertification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerintegrationlog',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='lms.certificationprovider'),
        ),
        migrations.AddField(
            model_name='intakeenrollment',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.courseintake'),
        ),
        migrations.AddField(
            model_name='intakeenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='lms.certification'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='course_intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_registrations', to='lms.courseintake'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseintake',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='lms.course'),
        ),
        migrations.AddField(
            model_name='courseintake',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseintake',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['instructor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificationprovider',
            index=models.Index(fields=['name', 'is_active'], name='lms_certifi_name_84320f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificationprovider',
            index=models.Index(fields=['provider_type', 'partnership_status'], name='lms_certifi_provide_0637ae_idx'),
        ),
        migrations.AddField(
            model_name='certification',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='lms.certificationprovider'),
        ),
        migrations.AddField(
            model_name='certification',
            name='synego_course',
            field=models.ForeignKey(blank=True, help_text='Corresponding Synego course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='lms.course'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lms.courseintake'),
        ),
        migrations.AddField(
            model_name='courseadvertisement',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='lms.courseintake'),
        ),
        migrations.AddField(
            model_name='coursereminder',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lms.courseintake'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.intakeenrollment'),
        ),
        migrations.AddIndex(
            model_name='studentcertification',
            index=models.Index(fields=['student', 'is_active'], name='lms_student_student_cc9665_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcertification',
            index=models.Index(fields=['certificate_number'], name='lms_student_certifi_8e4c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerintegrationlog',
            index=models.Index(fields=['provider', 'success'], name='lms_partner_provide_3b4fee_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerintegrationlog',
            index=models.Index(fields=['created_at'], name='lms_partner_created_067885_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intakeenrollment',
            unique_together={('intake', 'student')},
        ),
        migrations.AddIndex(
            model_name='examregistration',
            index=models.Index(fields=['student', 'status'], name='lms_examreg_student_3a3dad_idx'),
        ),
        migrations.AddIndex(
            model_name='examregistration',
            index=models.Index(fields=['certification', 'status'], name='lms_examreg_certifi_dbd4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='examregistration',
            index=models.Index(fields=['voucher_code'], name='lms_examreg_voucher_d29d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='examregistration',
            index=models.Index(fields=['provider_reference'], name='lms_examreg_provide_447213_idx'),
        ),
        migrations.AddIndex(
            model_name='courseintake',
            index=models.Index(fields=['course_start_date', 'status'], name='lms_coursei_course__241a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='courseintake',
            index=models.Index(fields=['course', 'is_visible', 'is_featured'], name='lms_coursei_course__6ba65a_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['provider', 'is_active'], name='lms_certifi_provide_129a11_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['code'], name='lms_certifi_code_6f7e16_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['difficulty'], name='lms_certifi_difficu_f82174_idx'),
        ),
    ]
