# Generated by Django 5.2.13 on 2026-05-02 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_certification_certificationprovider_courseintake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Engineering Assignment', 'Grading Document')", max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the document')),
                ('document_type', models.CharField(choices=[('assignment', 'Assignment Document'), ('grading', 'Grading Document'), ('student_register', 'Student Register'), ('grade_sheet', 'Grade Sheet'), ('course_material', 'Course Material'), ('exam', 'Exam/Test'), ('attendance', 'Attendance Sheet'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='stored_documents/%Y/%m/%d/')),
                ('file_size_mb', models.FloatField(default=0.0, editable=False)),
                ('file_extension', models.CharField(editable=False, max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Can other users access this document?')),
                ('can_download', models.BooleanField(default=True, help_text='Allow users to download this document')),
                ('can_view_online', models.BooleanField(default=True, help_text='Allow online preview/viewing')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'engineering, surveying, assignment')", max_length=500)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'permissions': [('can_share_document', 'Can share documents with others'), ('can_delete_all_documents', 'Can delete any document')],
            },
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_documents', to='lms.course'),
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='related_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_documents', to='lms.assignment'),
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentstorage',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='lms_documen_uploade_93b98b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstorage',
            index=models.Index(fields=['document_type'], name='lms_documen_documen_e4674d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstorage',
            index=models.Index(fields=['course'], name='lms_documen_course__591d40_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstorage',
            index=models.Index(fields=['name'], name='lms_documen_name_5c4f1b_idx'),
        ),
    ]
